// Build script: reads API_URL from environment variables and writes js/config.js
// Run by Vercel before deployment via vercel.json buildCommand
const fs = require('fs');

const apiUrl = process.env.API_URL || '';

const configContent = `// Auto-generated by generate-config.js — do not edit manually
const BACKEND_URL = "${apiUrl}";
`;

fs.writeFileSync('js/config.js', configContent);
console.log(`✅ config.js generated with API_URL = "${apiUrl || '(empty — relative paths)'}"`);
